const pages: Record<string, string> = {
  '/': '<!doctype html><html lang="fr"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Présentation — Calendly Contacts Agathe</title><style>body{font:18px/1.6 system-ui;max-width:760px;margin:48px auto;padding:0 24px;color:#20332b}nav{display:flex;gap:20px;flex-wrap:wrap}a{color:#245e48}</style><nav><a href="/">Présentation</a><a href="/privacy">Confidentialité</a><a href="/terms">Conditions d’utilisation</a></nav><main><h1>Présentation — Calendly Contacts Agathe</h1><p>Outil privé utilisé par Agathe Lescout pour synchroniser ses réservations Calendly vers son compte Google Contacts. Il importe l’historique disponible et met à jour les contacts lors des nouvelles réservations et annulations.</p><p>L’autorisation Google permet au programme de rechercher les contacts existants, de créer ou compléter leurs coordonnées, d’ajouter le libellé Calendly et de conserver des informations sur les consultations dans les notes. Une annulation conserve le contact. Le programme est configuré pour un seul compte destinataire.\n</p></main></html>',
  '/privacy':
    '<!doctype html><html lang="fr"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Confidentialité — Calendly Contacts Agathe</title><style>body{font:18px/1.6 system-ui;max-width:760px;margin:48px auto;padding:0 24px;color:#20332b}nav{display:flex;gap:20px;flex-wrap:wrap}a{color:#245e48}</style><nav><a href="/">Présentation</a><a href="/privacy">Confidentialité</a><a href="/terms">Conditions d’utilisation</a></nav><main><h1>Confidentialité — Calendly Contacts Agathe</h1><p>Le service utilise les noms, adresses e-mail, téléphones et réponses aux questions des réservations Calendly. Il accède aux contacts Google afin d’éviter les doublons et de préserver les coordonnées, libellés et notes existants.</p><p>Les réservations, correspondances avec les contacts Google et informations de traitement sont stockées dans une base Cloudflare D1 dédiée en Union européenne. Les jetons d’accès sont enregistrés comme secrets Cloudflare. Les données sont traitées par Calendly, Cloudflare et Google pour réaliser cette synchronisation.</p><p>Les données ne servent ni à la publicité ni à l’entraînement de modèles d’intelligence artificielle. Les journaux applicatifs ne contiennent pas les coordonnées, réponses des invités ou jetons. Le code cherche à préserver les notes manuelles et signale les conflits de modification.</p><p>Le service n’effectue pas de suppression automatique des données historiques. Agathe peut suspendre la synchronisation, révoquer les autorisations dans Google ou Calendly et demander la suppression des données de la base dédiée. Révoquer l’accès ne supprime pas les contacts déjà présents dans Google Contacts.</p><p>Contact : agathe.lescout.osteo@gmail.com.\n</p></main></html>',
  '/terms':
    '<!doctype html><html lang="fr"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Conditions d’utilisation — Calendly Contacts Agathe</title><style>body{font:18px/1.6 system-ui;max-width:760px;margin:48px auto;padding:0 24px;color:#20332b}nav{display:flex;gap:20px;flex-wrap:wrap}a{color:#245e48}</style><nav><a href="/">Présentation</a><a href="/privacy">Confidentialité</a><a href="/terms">Conditions d’utilisation</a></nav><main><h1>Conditions d’utilisation — Calendly Contacts Agathe</h1><p>Cette application est un outil privé destiné à Agathe Lescout. Elle ne propose pas d’inscription ni de service à des utilisateurs externes. Son fonctionnement dépend des autorisations accordées à Calendly et Google ainsi que de la disponibilité de ces services et de Cloudflare. Les conflits signalés doivent être vérifiés avant de poursuivre les écritures concernées.</p></main></html>',
};

export function publicPage(path: string): Response | undefined {
  const body = pages[path];
  if (!body) return undefined;
  return new Response(body, {
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
      'X-Content-Type-Options': 'nosniff',
      'Referrer-Policy': 'no-referrer',
      'Content-Security-Policy':
        "default-src 'none'; style-src 'unsafe-inline'; frame-ancestors 'none'",
    },
  });
}
