import assert from 'node:assert/strict';
import test from 'node:test';
import {
  createDemoReport,
  demoConsultationPdf,
} from '../scripts/demo-report.mjs';
import {
  createDemoData,
  createDemoTransport,
} from '../scripts/preview-data.mjs';

test('demo reports are available only when their PDF is supported, for the matching contact', async () => {
  const now = new Date('2026-10-08T08:15:00Z');
  const data = createDemoData(now);
  const contact = data.contacts[2]!;
  const document = createDemoReport(contact);
  const path = '/api/consultation-reports?contactId=people%2Fdemo3';
  assert.deepEqual(await createDemoTransport(data)(path), { reports: [] });

  const transport = createDemoTransport(data, {
    reports: [{ contactId: document.contactId, ...document.report }],
  });
  assert.deepEqual(await transport(path), { reports: [document.report] });
  assert.deepEqual(
    await transport('/api/consultation-reports?contactId=people%2Fdemo4'),
    { reports: [] }
  );
  assert.ok(
    Date.parse(document.report.date) > Date.parse(contact.lastAppointment!)
  );
  assert.ok(Date.parse(document.report.date) < +now);
  assert.equal(document.report.type, 'consultation-report');
  assert.equal(document.report.size, document.pdf.length);
});

test('demo PDF endpoint serves the generated bytes, supports HEAD and rejects unknown documents', async () => {
  const document = createDemoReport(createDemoData().contacts[2]);
  const response = demoConsultationPdf(document, document.report.id);
  assert.equal(response.status, 200);
  assert.equal(response.headers.get('content-type'), 'application/pdf');
  assert.match(
    response.headers.get('content-disposition')!,
    /compte-rendu-oslo-demo\.pdf/
  );
  const bytes = Buffer.from(await response.arrayBuffer());
  assert.deepEqual(bytes, document.pdf);
  assert.match(bytes.toString('latin1'), /^%PDF-1\.4/);
  assert.match(bytes.toString('latin1'), /DONNÉES ENTIÈREMENT FICTIVES/);
  assert.match(bytes.toString('latin1'), /Compte rendu envoyé le/);
  assert.equal(demoConsultationPdf(document, 'unknown').status, 404);
  assert.equal(
    demoConsultationPdf(document, document.report.id, 'POST').status,
    405
  );
  const head = demoConsultationPdf(document, document.report.id, 'HEAD');
  assert.equal(head.status, 200);
  assert.equal(await head.text(), '');
  assert.equal(
    head.headers.get('content-length'),
    String(document.report.size)
  );
});
